import { SubTitleContentProps } from "../components/SubTitle";

export const tutorialSubTitle: SubTitleContentProps[] = [
  { text: '哈喽大家好, 这里是萌苏恩uwu' },
  { text: '这是一期全流程的游戏开发教程' },
  { text: '主要面向完全不知道如何开始的初学者' },
  { text: '在一切开始之前,我希望你记住' },
  { text: '最重要的一点是别想太多, 先照着我说的做' },
  { text: '你也许了解过，有很多游戏引擎可以选择' },
  { text: '但如果我一一把它们列出来,一个个分析过去, 只会让你更困惑, 在这里, 我想向你推荐, bevy' },
  { text: '接下来我们直接进入准备步骤, 先去下载vscode,它会成为我们之后一直使用的编辑器' },
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
  { text: ''},
]